name: merge to main workflow

on:
  push:
    branches: [main]

env:
  BRANCH_NAME: ${{ github.event.ref.BRANCH_NAME }}

jobs:
  get_commit_id:
    runs-on: ubuntu-22.04
    outputs:
      commit_id: ${{ steps.commit_id.outputs.commit_id }}
    steps:
      - name: Get Commit ID
        id: commit_id
        run: |
          echo "commit_id=${{ github.sha }}" >> "$GITHUB_OUTPUT"

  package_code:
    needs: [get_commit_id]
    uses: ./.github/workflows/cdk_package_code.yml
    with:
      VERSION_NUMBER: "hack"
      COMMIT_ID: ${{needs.get_commit_id.outputs.commit_id}}

  release_dev:
    needs: [package_code, get_commit_id]
    uses: ./.github/workflows/release_all_stacks.yml
    with:
      SERVICE_NAME: hackapp
      TARGET_ENVIRONMENT: dev
      VERSION_NUMBER: "hack"
      COMMIT_ID: ${{needs.get_commit_id.outputs.commit_id}}
      LOG_LEVEL: "DEBUG"
      ROUTE53_EXPORT_NAME: EPS
      REACT_LOG_LEVEL: "debug"
      LOG_RETENTION_IN_DAYS: 30
      IS_PULL_REQUEST: false
    secrets: inherit
